FROM nginx

# Remove any default nginx configs
RUN rm -f /etc/nginx/conf.d/* /etc/nginx/nginx.conf

# Copy public-facing files
COPY ./dist/client/public /usr/share/nginx/html/

COPY ./nginx/client.conf /etc/nginx/nginx.conf

EXPOSE 80
